# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cyf/work/fetch_12306/script/chapter3/12306.git/ui/mainwindow.ui'
#
# Created: Fri Oct 30 21:00:16 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(814, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cmbFrom = QtGui.QComboBox(self.centralWidget)
        self.cmbFrom.setEditable(True)
        self.cmbFrom.setObjectName(_fromUtf8("cmbFrom"))
        self.horizontalLayout.addWidget(self.cmbFrom)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbTo = QtGui.QComboBox(self.centralWidget)
        self.cmbTo.setEditable(True)
        self.cmbTo.setObjectName(_fromUtf8("cmbTo"))
        self.horizontalLayout.addWidget(self.cmbTo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.dateStart = QtGui.QDateEdit(self.centralWidget)
        self.dateStart.setDate(QtCore.QDate(2015, 10, 15))
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName(_fromUtf8("dateStart"))
        self.horizontalLayout.addWidget(self.dateStart)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnQuery = QtGui.QPushButton(self.centralWidget)
        self.btnQuery.setObjectName(_fromUtf8("btnQuery"))
        self.horizontalLayout.addWidget(self.btnQuery)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainsplitter = QtGui.QSplitter(self.centralWidget)
        self.mainsplitter.setOrientation(QtCore.Qt.Vertical)
        self.mainsplitter.setObjectName(_fromUtf8("mainsplitter"))
        self.tableTickets = QtGui.QTableWidget(self.mainsplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.tableTickets.sizePolicy().hasHeightForWidth())
        self.tableTickets.setSizePolicy(sizePolicy)
        self.tableTickets.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableTickets.setRowCount(0)
        self.tableTickets.setColumnCount(16)
        self.tableTickets.setObjectName(_fromUtf8("tableTickets"))
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(15, item)
        self.tableTickets.horizontalHeader().setCascadingSectionResizes(False)
        self.tableTickets.horizontalHeader().setMinimumSectionSize(56)
        self.tableTickets.horizontalHeader().setStretchLastSection(False)
        self.tableTickets.verticalHeader().setStretchLastSection(False)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.mainsplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.mainsplitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.action_login = QtGui.QAction(MainWindow)
        self.action_login.setObjectName(_fromUtf8("action_login"))
        self.action_tickets = QtGui.QAction(MainWindow)
        self.action_tickets.setObjectName(_fromUtf8("action_tickets"))
        self.action_fresh_tickets = QtGui.QAction(MainWindow)
        self.action_fresh_tickets.setObjectName(_fromUtf8("action_fresh_tickets"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "12306定票软件", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "出发地：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "目的地：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "出发日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuery.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "车次", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "出发站", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "到达站", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "出发时间", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "达到时间", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "历时", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "商务座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "特等座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "一等座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "二等座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "高级软卧", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("MainWindow", "软卧", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(12)
        item.setText(QtGui.QApplication.translate("MainWindow", "硬卧", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(13)
        item.setText(QtGui.QApplication.translate("MainWindow", "软座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(14)
        item.setText(QtGui.QApplication.translate("MainWindow", "硬座", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableTickets.horizontalHeaderItem(15)
        item.setText(QtGui.QApplication.translate("MainWindow", "无座", None, QtGui.QApplication.UnicodeUTF8))
        self.action_login.setText(QtGui.QApplication.translate("MainWindow", "用户登录", None, QtGui.QApplication.UnicodeUTF8))
        self.action_tickets.setText(QtGui.QApplication.translate("MainWindow", "定时抢票", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fresh_tickets.setText(QtGui.QApplication.translate("MainWindow", "自动刷票", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

